"""initial schema

Revision ID: 47e0afd9857d
Revises: 
Create Date: 2026-09-06 01:12:46.737525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47e0afd9857d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('app_version', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('passcode_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_id'), 'devices', ['device_id'], unique=True)
    op.create_table('calibrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('correction', sa.Float(), nullable=False),
    sa.Column('reference_name', sa.String(), nullable=False),
    sa.Column('reference_mm', sa.Float(), nullable=False),
    sa.Column('measured_px', sa.Integer(), nullable=False),
    sa.Column('diopters', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibrations_device_id'), 'calibrations', ['device_id'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('ruleset_version', sa.String(), nullable=False),
    sa.Column('sku_id', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('mrp', sa.String(), nullable=True),
    sa.Column('net_quantity', sa.String(), nullable=True),
    sa.Column('batch_number', sa.String(), nullable=True),
    sa.Column('mfg_date', sa.String(), nullable=True),
    sa.Column('frames_used', sa.Integer(), nullable=False),
    sa.Column('raw_lines', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_device_id'), 'scans', ['device_id'], unique=False)
    op.create_index(op.f('ix_scans_sku_id'), 'scans', ['sku_id'], unique=False)
    op.create_index(op.f('ix_scans_verdict'), 'scans', ['verdict'], unique=False)
    op.create_table('skus',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sku_id', sa.String(), nullable=False),
    sa.Column('authority', sa.String(), nullable=False),
    sa.Column('brand_strings', sa.JSON(), nullable=False),
    sa.Column('addresses', sa.JSON(), nullable=False),
    sa.Column('consumer_care', sa.JSON(), nullable=False),
    sa.Column('mrp_exact', sa.Float(), nullable=True),
    sa.Column('net_quantity', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('enrolled_by_device_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enrolled_by_device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skus_sku_id'), 'skus', ['sku_id'], unique=True)
    op.create_table('scan_checks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('rule_name', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('citation', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('observed_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'rule_id', name='uq_scan_check_rule')
    )
    op.create_index(op.f('ix_scan_checks_scan_id'), 'scan_checks', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_checks_scan_id'), table_name='scan_checks')
    op.drop_table('scan_checks')
    op.drop_index(op.f('ix_skus_sku_id'), table_name='skus')
    op.drop_table('skus')
    op.drop_index(op.f('ix_scans_verdict'), table_name='scans')
    op.drop_index(op.f('ix_scans_sku_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_device_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_calibrations_device_id'), table_name='calibrations')
    op.drop_table('calibrations')
    op.drop_index(op.f('ix_devices_device_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
