"""add matches registry

Revision ID: e8b7cfdb45c4
Revises: 1a1a94272376
Create Date: 2026-09-06 02:59:11.827055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b7cfdb45c4'
down_revision: Union[str, Sequence[str], None] = '1a1a94272376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches_registry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.String(), nullable=False),
    sa.Column('sku_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rejection_threshold', sa.Float(), nullable=False),
    sa.Column('match_method', sa.String(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('extracted_identity', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_registry_scan_id'), 'matches_registry', ['scan_id'], unique=False)
    op.create_index(op.f('ix_matches_registry_sku_id'), 'matches_registry', ['sku_id'], unique=False)
    op.create_index(op.f('ix_matches_registry_status'), 'matches_registry', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_registry_status'), table_name='matches_registry')
    op.drop_index(op.f('ix_matches_registry_sku_id'), table_name='matches_registry')
    op.drop_index(op.f('ix_matches_registry_scan_id'), table_name='matches_registry')
    op.drop_table('matches_registry')
    # ### end Alembic commands ###
